### ISSUE TITLE
Can not install grunt-bump

### ISSUE THREAD

**Issue by cristian-sima** [vojtajina/grunt-bump#181] opened 2016-04-19 13:30 UTC
Hi. I want to install it using npm and I got this

![image](https://cloud.githubusercontent.com/assets/12199042/14640797/ee6cbb6e-064b-11e6-97cf-02cf1dc8db37.png)

The log is
[npm-debug.zip](https://github.com/vojtajina/grunt-bump/files/225965/npm-debug.zip)

**Comment by giltron** [comment] 2016-04-19 18:04
Also encountered this unexpected issue. Duplicate of #180

**Closed** 2016-04-19 18:17 UTC

**Comment by eddiemonge** [comment] 2016-04-19 19:02
Try again now

**Comment by michelem09** [comment] 2016-09-11 17:48
I have same problem 

```
npm 2.14.20
node 4.4.0
```

> npm WARN peerDependencies The peer dependency grunt@>=1.0.1 included from grunt-bump will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> /
> 
> npm ERR! Darwin 16.0.0
> npm ERR! argv "/Users/michele/.nvm/versions/node/v4.4.0/bin/node" "/Users/michele/.nvm/versions/node/v4.4.0/bin/npm" "install" "grunt-bump" "--save-dev"
> npm ERR! node v4.4.0
> npm ERR! npm  v2.14.20
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package grunt@0.4.5 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer grunt-mocha-istanbul@3.0.1 wants grunt@0.4.x
> npm ERR! peerinvalid Peer grunt-node-inspector@0.4.1 wants grunt@^0.4.5
> npm ERR! peerinvalid Peer grunt-contrib-copy@0.8.2 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-bump@0.8.0 wants grunt@>=1.0.1
> npm ERR! peerinvalid Peer grunt-karma@0.12.2 wants grunt@>=0.4.x
> npm ERR! peerinvalid Peer grunt-ng-constant@2.0.1 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-contrib-csslint@0.4.0 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-contrib-sass@1.0.0 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
> npm ERR! peerinvalid Peer grunt-ng-annotate@1.0.1 wants grunt@~0.4.5
> npm ERR! peerinvalid Peer load-grunt-tasks@3.5.2 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
> npm ERR! peerinvalid Peer grunt-contrib-less@1.0.1 wants grunt@~0.4.5
> npm ERR! peerinvalid Peer grunt-protractor-runner@3.0.0 wants grunt@~0.4.1
> npm ERR! peerinvalid Peer grunt-contrib-cssmin@0.12.3 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-nodemon@0.4.2 wants grunt@>=0.4.0

**Comment by michelem09** [comment] 2016-09-11 17:50
Latest installable (for me) is 0.7.0
