### ISSUE TITLE
A commit="true" bug in case a working dir is not a git root?..

### ISSUE THREAD

**Issue by dmytro-shchurov** [vojtajina/grunt-bump#115] opened 2015-01-08 12:43 UTC
We use a version bumping in a git pre-commit hook. It's possible with `grunt-githook` module. Our git root is not the same as a working dir. A working dir does not contain any `.git` folder nor a file.

When stages files are committed, the `bump` updates versions in few config files. If `commit=false`, the changes remain not staged. When `commit=true` a fatal error occurs.

Here are a simple settings of the task:
```
options: {
                files: ['package.json'],
                updateConfigs: ['pkg'],
                commit: true,
                createTag: false,
                globalReplace: false,
                push: false
            }
```

Here is a fatal error:
```
[4mRunning "bump" task[24m
[32m>> [39mVersion bumped to 1.0.9
[32m>> [39mpkg's version updated
[31mFatal error: Can not create the commit:
  fatal: Not a git repository: '.git'
[39m
```

I realise that may be I use the module in a wrong way, and the best is just to update the version with something like `json2js`, but the module provides a bunch of interesting functionality we might use in the future.. Alongside, we'd like the modified files to be staged/committed and ready for pre-commit git hook.

**Comment by eddiemonge** [comment] 2015-01-29 01:14
You can't commit to a git repo files that are not in a git repo. Maybe you should just use this to update the files and then the rest of the hook to commit them. Closing this as a process error, not a bug.

**Closed by eddiemonge** 2015-01-29 01:14 UTC
